# Для администраторов
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: Group
  name: admins
  apiGroup: rbac.authorization.k8s.io
---
# Для editor
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: editor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: editor
subjects:
- kind: Group
  name: editor
  apiGroup: rbac.authorization.k8s.io
---
# Для аналитиков, разработчиков viewer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- kind: Group
  name: viewers
  apiGroup: rbac.authorization.k8s.io
